### ISSUE TITLE
Properly size specific images

### ISSUE THREAD

**Issue by RobertRR11** [Faithful-Resource-Pack/Website#46]
There are some specific images, for example the release posts on the main page, which display very small. Due to a user very likely not visiting all posts, the posts on the main page should be served with a much smaller size to optimize loading times.
But this process of creating a smaller size image of the full resolution image should be automated for obvious reasons.

Lighthouse recommendation: 
![image](https://user-images.githubusercontent.com/57044042/151219457-017afc48-9ff4-4a47-b41b-ceffaa9f73c2.png)

Full Lighthouse report: (Github doesn't allow uploading html's smh)
[compliancepack.net_2022-01-26_18-34-55.html.zip](https://github.com/Compliance-Resource-Pack/Website/files/7944080/compliancepack.net_2022-01-26_18-34-55.html.zip)

**Comment by TheRolfFR** [comment]
**Note**: Max image width is 545px scaled to 110% on hover so 599.5 -> 600px

**Comment by RobertRR11** [comment]
Also I mean this for images in general that are used multiple times in different sizes, not just the articles.

**Comment by Juknum** [comment]
You can now dynamically resize images from the database using a specific URL query :

- basic size: 
https://database.faithfulpack.net/images/bot/coin_heads.png

- smaller:
 https://database.faithfulpack.net/images/bot/coin_heads.png?w=12
`w` & `h` are respectively for the width and height, **if only one is provided, the aspect ratio is conserved**.

- bigger: 
https://database.faithfulpack.net/images/bot/coin_heads.png?w=240&enlarge=1 
To extend it, you'll need the `enlarge=1` property;

As far as I remember, images are cached & stored on the server. The first query takes some seconds (due to image generation) but after that, it's "instantaneous" as it has already been generated.
